# these are all the main text figures.
# Fig5.tif and Fig6.tif are generated by Fig4.R along with Fig4.tif
# so they need to be listed explicitly
FIGS := $(patsubst %.R,%.tif,$(wildcard Fig*.R)) Fig5.tif Fig6.tif

FIGS_PDF := $(FIGS:.tif=.pdf)

# there is only one table, but why not be consistent?
TABLES := $(patsubst %.R,%.tex,$(wildcard Table*.R))

# these figures are for the supporting information
# or for the manuscript repo:
FIGS_AGENCY := agency-comparisons/hepatitis-A-B-ontario.png
FIGS_AGENCY += agency-comparisons/poliomyelitis-ontario.png
FIGS_AGENCY += agency-comparisons/salmonellosis-ontario.png
FIGS_AGENCY += agency-comparisons/syphilis-ontario.png
FIGS_AGENCY += agency-comparisons/whooping-cough-ontario.png
FIGS_PORTAL += phac-portal-comparisons/Creutzfeldt-Jakob-disease.png
FIGS_PORTAL += phac-portal-comparisons/AIDS.png
FIGS_PORTAL += phac-portal-comparisons/HIV.png
FIGS_PORTAL += phac-portal-comparisons/acute-flaccid-paralysis.png
FIGS_PORTAL += phac-portal-comparisons/amoebic-dysentery.png
FIGS_PORTAL += phac-portal-comparisons/anthrax.png
FIGS_PORTAL += phac-portal-comparisons/bacillary-dysentery.png
FIGS_PORTAL += phac-portal-comparisons/botulism.png
FIGS_PORTAL += phac-portal-comparisons/brucellosis.png
FIGS_PORTAL += phac-portal-comparisons/campylobacteriosis.png
FIGS_PORTAL += phac-portal-comparisons/chickenpox.png
FIGS_PORTAL += phac-portal-comparisons/chlamydia.png
FIGS_PORTAL += phac-portal-comparisons/cholera.png
FIGS_PORTAL += phac-portal-comparisons/congenital-rubella.png
FIGS_PORTAL += phac-portal-comparisons/cryptosporidiosis.png
FIGS_PORTAL += phac-portal-comparisons/cyclosporiasis.png
FIGS_PORTAL += phac-portal-comparisons/diphtheria.png
FIGS_PORTAL += phac-portal-comparisons/dysentery_unspecified.png
FIGS_PORTAL += phac-portal-comparisons/food-poisoning.png
FIGS_PORTAL += phac-portal-comparisons/giardiasis.png
FIGS_PORTAL += phac-portal-comparisons/gonococcal-infections.png
FIGS_PORTAL += phac-portal-comparisons/group-A-strep.png
FIGS_PORTAL += phac-portal-comparisons/group-B-strep-neonates.png
FIGS_PORTAL += phac-portal-comparisons/hantavirus-pulmonary-syndrome.png
FIGS_PORTAL += phac-portal-comparisons/hepatitis-A.png
FIGS_PORTAL += phac-portal-comparisons/hepatitis-B.png
FIGS_PORTAL += phac-portal-comparisons/hepatitis-C.png
FIGS_PORTAL += phac-portal-comparisons/hepatitis_ex-A_ex-B.png
FIGS_PORTAL += phac-portal-comparisons/hepatitis_unspecified.png
FIGS_PORTAL += phac-portal-comparisons/influenza.png
FIGS_PORTAL += phac-portal-comparisons/invasive-pneumococcal-disease.png
FIGS_PORTAL += phac-portal-comparisons/legionellosis.png
FIGS_PORTAL += phac-portal-comparisons/leprosy.png
FIGS_PORTAL += phac-portal-comparisons/listeriosis.png
FIGS_PORTAL += phac-portal-comparisons/lyme-disease.png
FIGS_PORTAL += phac-portal-comparisons/malaria.png
FIGS_PORTAL += phac-portal-comparisons/measles.png
FIGS_PORTAL += phac-portal-comparisons/meningitis-bacterial.png
FIGS_PORTAL += phac-portal-comparisons/meningococcal-infections.png
FIGS_PORTAL += phac-portal-comparisons/mumps.png
FIGS_PORTAL += phac-portal-comparisons/paratyphoid-fever.png
FIGS_PORTAL += phac-portal-comparisons/plague.png
FIGS_PORTAL += phac-portal-comparisons/poliomyelitis.png
FIGS_PORTAL += phac-portal-comparisons/rabies.png
FIGS_PORTAL += phac-portal-comparisons/rubella.png
FIGS_PORTAL += phac-portal-comparisons/salmonellosis.png
FIGS_PORTAL += phac-portal-comparisons/scarlet-fever.png
FIGS_PORTAL += phac-portal-comparisons/smallpox.png
FIGS_PORTAL += phac-portal-comparisons/syphilis-congenital.png
FIGS_PORTAL += phac-portal-comparisons/syphilis.png
FIGS_PORTAL += phac-portal-comparisons/tetanus.png
FIGS_PORTAL += phac-portal-comparisons/trichinosis.png
FIGS_PORTAL += phac-portal-comparisons/tuberculosis.png
FIGS_PORTAL += phac-portal-comparisons/tularemia.png
FIGS_PORTAL += phac-portal-comparisons/typhoid-fever.png
FIGS_PORTAL += phac-portal-comparisons/typhoid-paratyphoid-fever.png
FIGS_PORTAL += phac-portal-comparisons/verotoxigenic-Escherichia-coli.png
FIGS_PORTAL += phac-portal-comparisons/viral-hemorrhagic-fever.png
FIGS_PORTAL += phac-portal-comparisons/west-nile-virus.png
FIGS_PORTAL += phac-portal-comparisons/whooping-cough.png
FIGS_PORTAL += phac-portal-comparisons/yellow-fever.png
FIGS_HIERARCHY += disease-hierarchies/hepatitis-A-B_1.png
FIGS_HIERARCHY += disease-hierarchies/hepatitis-A-B_2.png
FIGS_HIERARCHY += disease-hierarchies/hepatitis-A-B_3.png
FIGS_HIERARCHY += disease-hierarchies/hepatitis-A-B_4.png
FIGS_HIERARCHY += disease-hierarchies/hepatitis-A-B_5.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_1.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_2.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_3.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_4.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_5.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_6.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_7.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_8.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_9.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_10.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_11.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_12.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_13.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_14.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_15.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_16.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_17.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_18.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_19.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_20.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_21.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_22.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_23.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_24.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_25.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_26.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_27.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_28.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_29.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_30.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_31.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_32.png
FIGS_HIERARCHY += disease-hierarchies/meningitis_33.png

# these figures are actually used by ms.tex
USED_FLOATS := $(TABLES)
USED_FLOATS += agency-comparisons/whooping-cough-ontario.png
USED_FLOATS += meningitis_1.png
USED_FLOATS += meningitis_7.png
USED_FLOATS += meningitis_24.png
USED_FLOATS += meningitis_33.png
USED_FLOATS += hepatitis-A-B_3.png
USED_FLOATS += hepatitis-A-B_4.png
USED_FLOATS += chickenpox.png polio-hist.png

ALL_FIGS_AND_TABLES := $(FIGS) $(FIGS_PDF) $(TABLES) $(FIGS_AGENCY) $(FIGS_PORTAL) $(FIGS_HIERARCHY)
